import nodemailer from 'nodemailer'
import { SERVER_CONFIG } from '../config.js'
import type { ScrapedContact } from './contactScraper.js'
import type { AlertRecipient } from './alertRecipients.js'

// ─── Payload Types ────────────────────────────────────────────────────────────

export interface IncidentEmailPayload {
  incidentId: string
  severity: string
  incidentType: string
  location: string
  description: string
  affectedCount?: number
  urgencyFlags?: string[]
  lat?: number
  lng?: number
  // Extended for Super Critical ARIA format
  originalVoiceInput?: string
  suggestedResources?: string[]
  district?: string
  taluk?: string
  timestamp?: string
}

// ─── Email Template ───────────────────────────────────────────────────────────

function buildSuperCriticalHtml(payload: IncidentEmailPayload): string {
  const ts = payload.timestamp
    ? new Date(payload.timestamp).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })
    : new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })
  const resources = (payload.suggestedResources || []).join(', ') || 'Standard response units'
  const voiceInput = payload.originalVoiceInput || payload.description || 'Not recorded'

  return `
    <div style="font-family: monospace; background: #0a0a0a; color: #e0e0e0; padding: 24px; border-radius: 8px; max-width: 640px;">
      <h2 style="color: #ff4444; letter-spacing: 2px; border-bottom: 2px solid #ff4444; padding-bottom: 8px;">
        ⚠️ ARIA EMERGENCY ALERT — SUPER CRITICAL
      </h2>
      <div style="border: 1px solid #ff4444; border-radius: 4px; padding: 16px; margin: 16px 0; background: #1a0000;">
        <table style="width:100%; border-collapse:collapse; color:#e0e0e0;">
          <tr><td style="padding:4px 8px; color:#8888aa; width:160px;">Incident Type</td><td style="padding:4px 8px; font-weight:bold; color:#ff8888;">${payload.incidentType}</td></tr>
          <tr><td style="padding:4px 8px; color:#8888aa;">Location</td><td style="padding:4px 8px;">${payload.location}</td></tr>
          <tr><td style="padding:4px 8px; color:#8888aa;">Persons at Risk</td><td style="padding:4px 8px; color:#ffaa44; font-weight:bold;">${payload.affectedCount ?? 'Unknown'}</td></tr>
          <tr><td style="padding:4px 8px; color:#8888aa;">Severity</td><td style="padding:4px 8px; color:#ff4444; font-weight:bold; text-transform:uppercase;">${payload.severity}</td></tr>
          <tr><td style="padding:4px 8px; color:#8888aa;">Reported At</td><td style="padding:4px 8px;">${ts}</td></tr>
          ${payload.lat != null ? `<tr><td style="padding:4px 8px; color:#8888aa;">Coordinates</td><td style="padding:4px 8px; font-family:monospace;">${payload.lat?.toFixed(5)}, ${payload.lng?.toFixed(5)}</td></tr>` : ''}
          ${(payload.urgencyFlags || []).length > 0 ? `<tr><td style="padding:4px 8px; color:#8888aa;">Critical Flags</td><td style="padding:4px 8px; color:#ff8888;">${(payload.urgencyFlags || []).join(' · ')}</td></tr>` : ''}
          <tr><td style="padding:4px 8px; color:#8888aa;">Resources Needed</td><td style="padding:4px 8px;">${resources}</td></tr>
        </table>
      </div>

      <div style="border-left: 3px solid #ff4444; padding: 12px 16px; margin: 16px 0; background: #0f0000;">
        <div style="color:#8888aa; font-size:11px; margin-bottom:6px; letter-spacing:1px;">USER STATEMENT (VOICE INPUT)</div>
        <p style="color:#ffffff; font-style:italic; margin:0;">"${voiceInput}"</p>
      </div>

      <div style="margin-top: 16px; padding: 12px; background: #050505; border: 1px solid #333; border-radius: 4px;">
        <p style="color:#ff4444; font-weight:bold; margin:0 0 4px 0;">⚡ RESPOND IMMEDIATELY</p>
        <p style="color:#8888aa; margin:0; font-size:11px;">This alert was auto-generated by ARIA (Autonomous Relief Intelligence Assistant) — ReliefLens Tactical Node.</p>
      </div>
    </div>
  `
}

function buildEmailSubject(payload: IncidentEmailPayload): string {
  const ts = payload.timestamp
    ? new Date(payload.timestamp).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })
    : new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })
  return `[SUPER CRITICAL ALERT] ${payload.incidentType} — ${payload.location} — ${ts}`
}

// ─── Main Send Function ───────────────────────────────────────────────────────

export async function sendCriticalReport(
  scrapedContacts: ScrapedContact[],
  payload: IncidentEmailPayload,
  alertRecipients: AlertRecipient[] = []  // DB-sourced location-based recipients
): Promise<{ sent: string[]; failed: string[]; superCriticalSent: boolean }> {
  if (!SERVER_CONFIG.gmailUser || !SERVER_CONFIG.gmailAppPassword) {
    throw new Error(
      'Gmail not configured. Add GMAIL_USER and GMAIL_APP_PASSWORD (or GOOGLE_APP_PASSWORD) to .env.local.'
    )
  }

  const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
      user: SERVER_CONFIG.gmailUser,
      pass: SERVER_CONFIG.gmailAppPassword,
    },
  })

  const html = buildSuperCriticalHtml(payload)
  const subject = buildEmailSubject(payload)

  const sent: string[] = []
  const failed: string[] = []
  let superCriticalSent = false

  // 1. Send to official scraped contacts (up to 5 with valid emails)
  const contactRecipients = scrapedContacts.filter((c) => c.email).slice(0, 5)
  for (const contact of contactRecipients) {
    try {
      await transporter.sendMail({
        from: `ReliefLens ARIA Tactical <${SERVER_CONFIG.gmailUser}>`,
        to: contact.email,
        subject,
        html: `<p>Dear ${contact.name} (${contact.roleOrOrganization}),</p>${html}`,
        text: `[SUPER CRITICAL] Incident from ReliefLens ARIA.\n${JSON.stringify(payload, null, 2)}`,
      })
      sent.push(contact.email)
    } catch {
      failed.push(contact.email)
    }
  }

  // 2. Send to DB-sourced alert recipients (location-matched, not hardcoded)
  for (const recipient of alertRecipients) {
    if (sent.includes(recipient.email) || failed.includes(recipient.email)) continue
    try {
      await transporter.sendMail({
        from: `ReliefLens ARIA Tactical <${SERVER_CONFIG.gmailUser}>`,
        to: recipient.email,
        subject,
        html: `<p>ARIA Auto-Alert — Super Critical Report<br><small>${recipient.role}</small></p>${html}`,
        text: `[SUPER CRITICAL] ARIA Auto-Alert.\n${JSON.stringify(payload, null, 2)}`,
      })
      sent.push(recipient.email)
      superCriticalSent = true
      console.log(`[Email] Alert sent to DB recipient: ${recipient.email} (${recipient.role})`)
    } catch (err) {
      failed.push(recipient.email)
      console.error(`[Email] Failed to send to ${recipient.email}:`, err)
    }
  }

  return { sent, failed, superCriticalSent }
}
